rust:
  - changed-files:
    - any-glob-to-any-file: ["src/**/*.rs", "Cargo.toml", "Cargo.lock"]

tests:
  - changed-files:
    - any-glob-to-any-file: "tests/**"

ci:
  - changed-files:
    - any-glob-to-any-file: [".github/**", "Makefile"]

python:
  - changed-files:
    - any-glob-to-any-file: "**/*.py"

python-bindings:
  - changed-files:
    - any-glob-to-any-file: ["sgp4-predict-py/**", "**/*.pyi"]

documentation:
  - changed-files:
    - any-glob-to-any-file: ["**/*.md", "docs/**"]
