[package]
name = "sgp4-predict-py"
version = "0.2.0"
edition = "2024"
rust-version = "1.90"
publish = false
license = "MIT OR Apache-2.0"
repository = "https://github.com/steg87/sgp4-predict"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
sgp4-predict = { path = "../sgp4-predict", version = "0.2.1" }
pyo3 = { version = "0.29", features = ["chrono", "abi3-py310"] }
chrono = "0.4"
ouroboros = "0.18"
pyo3-stub-gen = "0.23"
serde_json = "1"

[[bin]]
name = "stub_gen"
path = "src/bin/stub_gen.rs"

[lints]
workspace = true
