# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import collections.abc
import datetime
import enum
import sgp4_predict
import typing
__all__ = [
    "AoiIter",
    "AoiWindow",
    "Apsis",
    "ApsisEvent",
    "ApsisIter",
    "Circle",
    "Classification",
    "Coverage",
    "Elements",
    "FillRule",
    "GeodeticPoint",
    "GroundTrackIter",
    "Illumination",
    "IlluminationIter",
    "IlluminationState",
    "Interval",
    "LatLon",
    "Observation",
    "ObservationIter",
    "Polygon",
    "PredictionIter",
    "Predictor",
    "Rectangle",
    "Refinement",
    "StateVectorEcef",
    "StateVectorEnu",
    "StateVectorTeme",
    "Tle",
    "Transit",
    "TransitIter",
    "Vec3",
]

@typing.final
class AoiIter:
    r"""
    Lazy iterator yielding the windows during which an area is within the payload's reach.
    """
    def __iter__(self) -> AoiIter: ...
    def __next__(self) -> AoiWindow: ...

@typing.final
class AoiWindow:
    r"""
    The window during which an area is within the payload's reach.
    """
    @property
    def start(self) -> datetime.datetime:
        r"""
        When the area comes within reach.
        """
    @property
    def end(self) -> datetime.datetime:
        r"""
        When it passes back out of reach.
        """
    @property
    def duration(self) -> datetime.timedelta:
        r"""
        Length of the interval.
        """
    @property
    def mid_point(self) -> datetime.datetime:
        r"""
        The instant halfway between `start` and `end`.
        """
    @property
    def duration_seconds(self) -> builtins.float:
        r"""
        Duration of the window in seconds.
        
        Deprecated: use `duration`, which is a `timedelta`.
        """
    def __eq__(self, other: builtins.object, /) -> builtins.bool: ...
    def __hash__(self) -> builtins.int: ...
    def intersection(self, other: sgp4_predict.IntervalRange) -> typing.Optional[Interval]:
        r"""
        The overlap with `other`, or None if the two do not overlap.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class Apsis:
    r"""
    A detected apsis event with refined time and altitude.
    """
    @property
    def time(self) -> datetime.datetime:
        r"""
        Time of the apsis event (UTC).
        """
    @property
    def event(self) -> ApsisEvent:
        r"""
        Whether this is an apogee or perigee.
        """
    @property
    def altitude(self) -> builtins.float:
        r"""
        Altitude above the WGS-84 equatorial radius in metres.
        """
    def __eq__(self, other: builtins.object, /) -> builtins.bool: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class ApsisIter:
    r"""
    Lazy iterator yielding apogee and perigee events within a time interval.
    """
    def __iter__(self) -> ApsisIter: ...
    def __next__(self) -> Apsis: ...

@typing.final
class Circle:
    r"""
    A circular area on Earth's surface — a spherical cap.
    
    The radius is angular: a degree of arc is about 111.2 km on the ground. The
    centre may be a `LatLon` object, a `GeodeticPoint` object whose altitude is ignored,
    or a `(latitude_deg, longitude_deg)` tuple.
    
    Raises `ValueError` if the radius is outside `(0, 90)`, if the centre's latitude
    is outside [-90, 90], or if any argument is `nan` or infinite.
    """
    @property
    def centre(self) -> LatLon:
        r"""
        The circle's centre.
        """
    @property
    def radius_deg(self) -> builtins.float:
        r"""
        The circle's angular radius, in degrees of arc.
        """
    def __new__(cls, centre: sgp4_predict.LatLonLike, radius_deg: builtins.float) -> Circle: ...
    def signed_angular_offset_deg(self, point: sgp4_predict.LatLonLike) -> builtins.float:
        r"""
        Signed angular offset of a point from the boundary, in degrees:
        positive inside, negative outside, zero on the boundary.
        """
    def max_angular_distance_deg(self, point: sgp4_predict.LatLonLike) -> builtins.float:
        r"""
        Angular distance from a point to the farthest point of the area, in
        degrees. This is what `coverage="full"` is measured against.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class Elements:
    r"""
    Orbital elements for a satellite.
    
    Holds the data needed to initialise an SGP4 propagator.  Can be constructed
    field-by-field or parsed directly from an OMM JSON string.
    
    Example — parsing from a Space-Track / Celestrak API response:
    
    ```python
    import requests
    from sgp4_predict import Elements, Predictor
    
    data = requests.get("https://celestrak.org/SOCRATES/...").json()
    elements = Elements.from_dict(data[0])
    predictor = Predictor(elements)
    ```
    
    Example — manual construction:
    
    ```python
    from datetime import datetime, timezone
    from sgp4_predict import Classification, Elements, Predictor
    
    elements = Elements(
        norad_id=25544,
        epoch=datetime(2020, 7, 12, 1, 19, 7, tzinfo=timezone.utc),
        mean_motion=15.49560532,
        eccentricity=0.0001771,
        inclination=51.6435,
        right_ascension=225.4004,
        argument_of_perigee=44.9625,
        mean_anomaly=5.1087,
        mean_motion_dot=0.00289036,
        drag_term=0.0049645,
        revolution_number=23587,
        object_name="ISS (ZARYA)",
    )
    predictor = Predictor(elements)
    ```
    """
    @property
    def object_name(self) -> typing.Optional[builtins.str]:
        r"""
        Satellite name (OBJECT_NAME), if present.
        """
    @property
    def norad_id(self) -> builtins.int:
        r"""
        NORAD catalog number (NORAD_CAT_ID).
        """
    @property
    def classification(self) -> Classification:
        r"""
        Classification type (CLASSIFICATION_TYPE).
        """
    @property
    def international_designator(self) -> typing.Optional[builtins.str]:
        r"""
        International designator (OBJECT_ID), if present.
        """
    @property
    def epoch(self) -> datetime.datetime:
        r"""
        Element set epoch in UTC (EPOCH).
        """
    @property
    def mean_motion_dot(self) -> builtins.float:
        r"""
        First derivative of mean motion / 2 (MEAN_MOTION_DOT), rev/day².
        """
    @property
    def mean_motion_ddot(self) -> builtins.float:
        r"""
        Second derivative of mean motion / 6 (MEAN_MOTION_DDOT), rev/day³.
        """
    @property
    def drag_term(self) -> builtins.float:
        r"""
        BSTAR drag term (BSTAR), 1/earth-radii.
        """
    @property
    def element_set_number(self) -> builtins.int:
        r"""
        Element set number (ELEMENT_SET_NO).
        """
    @property
    def inclination(self) -> builtins.float:
        r"""
        Inclination (INCLINATION), degrees.
        """
    @property
    def right_ascension(self) -> builtins.float:
        r"""
        Right ascension of ascending node (RA_OF_ASC_NODE), degrees.
        """
    @property
    def eccentricity(self) -> builtins.float:
        r"""
        Eccentricity (ECCENTRICITY).
        """
    @property
    def argument_of_perigee(self) -> builtins.float:
        r"""
        Argument of perigee (ARG_OF_PERICENTER), degrees.
        """
    @property
    def mean_anomaly(self) -> builtins.float:
        r"""
        Mean anomaly (MEAN_ANOMALY), degrees.
        """
    @property
    def mean_motion(self) -> builtins.float:
        r"""
        Mean motion (MEAN_MOTION), rev/day.
        """
    @property
    def revolution_number(self) -> builtins.int:
        r"""
        Revolution number at epoch (REV_AT_EPOCH).
        """
    @property
    def ephemeris_type(self) -> builtins.int:
        r"""
        Ephemeris type (EPHEMERIS_TYPE). Normally 0.
        """
    def __new__(cls, *, norad_id: builtins.int, epoch: datetime.datetime, mean_motion: builtins.float, eccentricity: builtins.float, inclination: builtins.float, right_ascension: builtins.float, argument_of_perigee: builtins.float, mean_anomaly: builtins.float, mean_motion_dot: builtins.float, mean_motion_ddot: builtins.float = 0.0, drag_term: builtins.float = 0.0, revolution_number: builtins.int = 0, object_name: typing.Optional[builtins.str] = None, classification: Classification = Classification.Unclassified, international_designator: typing.Optional[builtins.str] = None, element_set_number: builtins.int = 0, ephemeris_type: builtins.int = 0) -> Elements:
        r"""
        Construct orbital elements from individual fields.
        
        `epoch` must be a timezone-aware `datetime` (UTC).
        All angle fields (`inclination`, `right_ascension`, `argument_of_perigee`,
        `mean_anomaly`) are in **degrees**.
        `mean_motion` is in **rev/day**.
        """
    @staticmethod
    def from_json(json: builtins.str) -> Elements:
        r"""
        Parse an OMM JSON string into orbital elements.
        
        The JSON must use CCSDS OMM field names (`NORAD_CAT_ID`, `EPOCH`,
        `MEAN_MOTION`, `ECCENTRICITY`, etc.).  Both Celestrak and Space-Track
        JSON responses are supported.
        
        Raises `ValueError` if the JSON is malformed or missing required fields.
        """
    @staticmethod
    def from_dict(data: builtins.dict) -> Elements:
        r"""
        Parse an OMM dict into orbital elements.
        
        The dict must use CCSDS OMM field names (`NORAD_CAT_ID`, `EPOCH`,
        `MEAN_MOTION`, `ECCENTRICITY`, etc.).  Both Celestrak and Space-Track
        JSON responses are supported — pass the dict directly without serialising
        to a string first.
        
        Raises `ValueError` if the dict is missing required fields or has invalid values.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class GeodeticPoint:
    r"""
    A geodetic position on or above the WGS-84 ellipsoid.
    """
    @property
    def latitude_deg(self) -> builtins.float:
        r"""
        GeodeticPoint latitude in degrees (positive north).
        """
    @property
    def longitude_deg(self) -> builtins.float:
        r"""
        GeodeticPoint longitude in degrees (positive east).
        """
    @property
    def altitude(self) -> builtins.float:
        r"""
        Height above the WGS-84 ellipsoid in metres.
        """
    def __eq__(self, other: builtins.object, /) -> builtins.bool: ...
    def __new__(cls, latitude_deg: builtins.float, longitude_deg: builtins.float, altitude: builtins.float) -> GeodeticPoint: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class GroundTrackIter:
    r"""
    Lazy iterator yielding `(datetime, GeodeticPoint)` sub-satellite points at regular intervals.
    """
    def __iter__(self) -> GroundTrackIter: ...
    def __next__(self) -> tuple[datetime.datetime, GeodeticPoint]: ...

@typing.final
class Illumination:
    r"""
    A contiguous window of constant illumination state.
    """
    @property
    def start(self) -> datetime.datetime:
        r"""
        Start of the illumination window (UTC).
        """
    @property
    def end(self) -> datetime.datetime:
        r"""
        End of the illumination window (UTC).
        """
    @property
    def duration(self) -> datetime.timedelta:
        r"""
        Length of the interval.
        """
    @property
    def mid_point(self) -> datetime.datetime:
        r"""
        The instant halfway between `start` and `end`.
        """
    @property
    def duration_seconds(self) -> builtins.float:
        r"""
        Duration of the window in seconds.
        
        Deprecated: use `duration`, which is a `timedelta`.
        """
    @property
    def state(self) -> IlluminationState:
        r"""
        Illumination state (Sunlit or Eclipse).
        """
    def __eq__(self, other: builtins.object, /) -> builtins.bool: ...
    def __hash__(self) -> builtins.int: ...
    def intersection(self, other: sgp4_predict.IntervalRange) -> typing.Optional[Interval]:
        r"""
        The overlap with `other`, or None if the two do not overlap.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class IlluminationIter:
    r"""
    Lazy iterator yielding sunlit and eclipse windows within a time interval.
    """
    def __iter__(self) -> IlluminationIter: ...
    def __next__(self) -> Illumination: ...

@typing.final
class Interval:
    r"""
    A concrete `[start, end)` interval.
    """
    @property
    def start(self) -> datetime.datetime:
        r"""
        Inclusive start of the interval.
        """
    @property
    def end(self) -> datetime.datetime:
        r"""
        Exclusive end of the interval.
        """
    @property
    def duration(self) -> datetime.timedelta:
        r"""
        Length of the interval.
        """
    @property
    def mid_point(self) -> datetime.datetime:
        r"""
        The instant halfway between `start` and `end`.
        """
    def __eq__(self, other: builtins.object, /) -> builtins.bool: ...
    def __hash__(self) -> builtins.int: ...
    def intersection(self, other: sgp4_predict.IntervalRange) -> typing.Optional[Interval]:
        r"""
        The overlap with `other`, or None if the two do not overlap.
        """
    def __new__(cls, start: datetime.datetime, end: datetime.datetime) -> Interval: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class LatLon:
    r"""
    A point on Earth's surface, in degrees.
    
    Anywhere a `LatLon` is accepted, a plain `(latitude_deg, longitude_deg)`
    tuple works too.
    """
    @property
    def latitude_deg(self) -> builtins.float:
        r"""
        GeodeticPoint latitude in degrees (positive north).
        """
    @property
    def longitude_deg(self) -> builtins.float:
        r"""
        GeodeticPoint longitude in degrees (positive east).
        """
    def __eq__(self, other: builtins.object, /) -> builtins.bool: ...
    def __new__(cls, latitude_deg: builtins.float, longitude_deg: builtins.float) -> LatLon: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class Observation:
    r"""
    A point observation of a satellite from a ground location.
    
    Use `azimuth_deg` and `elevation_deg` for angular values.
    Range is in metres, range rate in m/s (positive = receding).
    """
    @property
    def range(self) -> builtins.float: ...
    @property
    def range_rate(self) -> builtins.float: ...
    @property
    def azimuth_deg(self) -> builtins.float:
        r"""
        Azimuth in degrees from north, measured clockwise, in `(-180, 180]`.
        """
    @property
    def elevation_deg(self) -> builtins.float:
        r"""
        Elevation above the horizon in degrees.
        """
    def __eq__(self, other: builtins.object, /) -> builtins.bool: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class ObservationIter:
    r"""
    Lazy iterator yielding time-stamped observations at regular intervals.
    """
    def __iter__(self) -> ObservationIter: ...
    def __next__(self) -> tuple[datetime.datetime, Observation]: ...

@typing.final
class Polygon:
    r"""
    A closed polygon on Earth's surface whose edges are great-circle arcs.
    
    The ring closes implicitly and vertex order does not matter. Vertices may be
    `LatLon` objects, `GeodeticPoint` objects whose altitude is ignored, or
    `(latitude_deg, longitude_deg)` tuples.
    
    Edges are great-circle arcs, so vertices at the same latitude are not joined
    along the parallel — the arc bows toward the nearer pole, growing with the
    square of the edge's longitude span. A 7° edge at 60°N bulges about 0.05°;
    vertices a quarter of the globe apart reach roughly 68°N. Use `Rectangle` when
    the region really is "these latitudes by these longitudes".
    
    Raises `ValueError` if fewer than three distinct vertices remain, if a latitude
    is outside [-90, 90], if a coordinate is `nan` or infinite, if consecutive
    vertices are antipodal, or if the polygon does not fit inside a hemisphere.
    """
    @property
    def vertices(self) -> builtins.list[LatLon]:
        r"""
        The polygon's vertices in ring order, after deduplication.
        """
    @property
    def fill_rule(self) -> FillRule:
        r"""
        How the interior of a self-intersecting ring is determined.
        """
    def __new__(cls, vertices: collections.abc.Iterable[sgp4_predict.LatLonLike], fill_rule: FillRule = FillRule.NonZero) -> Polygon: ...
    def signed_angular_offset_deg(self, point: sgp4_predict.LatLonLike) -> builtins.float:
        r"""
        Signed angular offset of a point from the boundary, in degrees:
        positive inside, negative outside, zero on the boundary.
        """
    def max_angular_distance_deg(self, point: sgp4_predict.LatLonLike) -> builtins.float:
        r"""
        Angular distance from a point to the farthest point of the area, in
        degrees. This is what `coverage="full"` is measured against.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class PredictionIter:
    r"""
    Lazy iterator yielding `(datetime, StateVectorTeme)` at regular intervals.
    """
    def __iter__(self) -> PredictionIter: ...
    def __next__(self) -> tuple[datetime.datetime, StateVectorTeme]: ...

@typing.final
class Predictor:
    r"""
    Parsed TLE with pre-computed SGP4 constants, ready for propagation.
    
    Construct from a `Tle` or `Elements`; then use its methods to propagate state vectors,
    compute ground observations, detect passes, find apsides, and query illumination.
    """
    @property
    def epoch(self) -> datetime.datetime:
        r"""
        The epoch of the TLE (UTC).
        """
    def __new__(cls, elements: Elements) -> Predictor:
        r"""
        Initialise SGP4 constants from pre-parsed orbital elements.
        
        Pass an `Elements` object — constructed manually, from `Elements.from_json`,
        or obtained from `Tle.to_elements`.
        
        Raises `ValueError` if element initialisation fails.
        """
    @staticmethod
    def from_tle(tle: Tle) -> Predictor:
        r"""
        Parse TLE string lines and initialise SGP4 constants.
        
        Raises `ValueError` if the TLE is malformed.
        """
    def with_refinement(self, refinement: Refinement) -> Predictor:
        r"""
        Return a new `Predictor` with the given root-finder configuration.
        """
    def propagate(self, t: datetime.datetime) -> StateVectorTeme:
        r"""
        Propagate the TLE to the given UTC time.
        
        Returns a state vector in the TEME frame.
        """
    def observe_at(self, t: datetime.datetime, observer: GeodeticPoint) -> Observation:
        r"""
        Calculate the observation from an observer at the given UTC time.
        """
    def prediction_iter(self, interval: sgp4_predict.IntervalRange, step: datetime.timedelta) -> PredictionIter:
        r"""
        Iterate over state vectors in the TEME frame at regular intervals.
        
        `interval` must expose `.start` and `.end` datetime properties.
        Pass an `Interval`, `Transit`, or `Illumination` object.
        """
    def observation_iter(self, observer: GeodeticPoint, interval: sgp4_predict.IntervalRange, step: datetime.timedelta) -> ObservationIter:
        r"""
        Iterate over observations from the given observer at regular intervals.
        
        `interval` must expose `.start` and `.end` datetime properties.
        Pass an `Interval`, `Transit`, or `Illumination` object.
        """
    def transits_iter(self, observer: GeodeticPoint, interval: sgp4_predict.IntervalRange, min_elevation_deg: builtins.float, *, min_step: typing.Optional[datetime.timedelta] = None, max_step: typing.Optional[datetime.timedelta] = None, walk_step: typing.Optional[datetime.timedelta] = None, max_transit_duration: typing.Optional[datetime.timedelta] = None, skip_leading_partial: typing.Optional[builtins.bool] = None, clamp_to_interval: typing.Optional[builtins.bool] = None) -> TransitIter:
        r"""
        Iterate over satellite passes visible to the observer within the interval.
        
        `interval` must expose `.start` and `.end` datetime properties.
        `min_elevation_deg`: minimum elevation above the horizon in degrees.
        
        The keyword-only arguments tune the coarse scan; each defaults to the
        library's own value.
        
        `min_step` and `max_step` bound the adaptive scan step: `min_step` is
        also the shortest pass the scan is guaranteed to see, and `max_step` is
        raised to it where it is smaller. `walk_step` is the fixed step used to
        walk from a transit's start to its end. A transit longer than
        `max_transit_duration` raises `RuntimeError`.
        
        `skip_leading_partial` discards a transit already in progress at the
        interval start; set it to `False` to walk backward for its true AoS.
        `clamp_to_interval` clamps a transit still in progress at the interval
        end to the interval, instead of walking forward for its true LoS.
        """
    def sub_point(self, t: datetime.datetime) -> GeodeticPoint:
        r"""
        The geodetic point directly beneath the satellite at time `t`.
        """
    def ground_track_iter(self, interval: sgp4_predict.IntervalRange, step: datetime.timedelta) -> GroundTrackIter:
        r"""
        Trace the satellite's ground track at regular intervals.
        
        `interval` must expose `.start` and `.end` datetime properties.
        Yields `(datetime, GeodeticPoint)` sub-satellite points.
        """
    def aoi_iter(self, area: sgp4_predict.Area, interval: sgp4_predict.IntervalRange, *, max_off_nadir_deg: typing.Optional[builtins.float] = None, coverage: typing.Optional[Coverage] = None, min_step: typing.Optional[datetime.timedelta] = None, max_step: typing.Optional[datetime.timedelta] = None, walk_step: typing.Optional[datetime.timedelta] = None, max_window_duration: typing.Optional[datetime.timedelta] = None, skip_leading_partial: typing.Optional[builtins.bool] = None, clamp_to_interval: typing.Optional[builtins.bool] = None) -> AoiIter:
        r"""
        Iterate over the windows in which `area` is within the payload's reach.
        
        `area` is a `Polygon`, `Rectangle`, or `Circle`.
        `interval` must expose `.start` and `.end` datetime properties.
        
        The keyword-only arguments tune the reach and the coarse scan; each defaults
        to the library's own value.
        
        `max_off_nadir_deg` is the half-angle of the satellite's field of regard —
        the largest nadir angle the payload can be slewed to. It defaults to zero,
        which detects the sub-satellite point itself crossing into the area. This is
        a field of *regard*, not of view: it describes everything the payload could
        be pointed at, not the footprint of a single image. A non-finite value is
        taken as zero. `coverage` chooses whether any part of the area
        (`Coverage.Any`, the default) or all of it (`Coverage.Full`) must be within
        reach; `Coverage.Full` needs `max_off_nadir_deg` set wider than the area,
        since at the default of zero the reach is a single point and no window
        ever opens.
        
        `min_step` is the lower bound of the adaptive coarse-scan step, and also the
        shortest crossing the scan is guaranteed to see; lower it below the default
        second for an area the ground track can cross faster than that. Floored at
        1 ms. `max_step` is the upper bound, used when the ground track is far from
        the area, and is raised to `min_step` where it is smaller — so a `min_step`
        above it pins the whole scan at that step and a small area will be stepped
        straight over. `walk_step` is the fixed step used to walk from a window's
        start to its end.
        
        `max_window_duration` caps how long a single window may run; the default is
        one hour. A window longer than the cap raises `RuntimeError`, so raise it for
        a continental-scale area — a LEO satellite is inside something like
        `Rectangle.latitude_band(-90.0, 60.0)` for most of each orbit.
        
        `skip_leading_partial` discards a window already in progress at the interval
        start; set it to `False` to walk backward for its true beginning.
        `clamp_to_interval` clamps a window still in progress at the interval end to
        the interval, instead of walking forward for its true end.
        """
    def detect_aoi(self, t: datetime.datetime, area: sgp4_predict.Area, *, max_off_nadir_deg: typing.Optional[builtins.float] = None, coverage: typing.Optional[Coverage] = None, walk_step: typing.Optional[datetime.timedelta] = None, max_window_duration: typing.Optional[datetime.timedelta] = None) -> typing.Optional[AoiWindow]:
        r"""
        Detect whether `area` is within the payload's reach at time `t`.
        
        Returns `None` if it is not. Otherwise searches backward and forward to
        bracket the entry and exit crossings.
        
        Raises `RuntimeError` if the window turns out to be longer than
        `max_window_duration`, which defaults to one hour. See `aoi_iter`; the
        other knobs there do not apply to this single-point detection.
        """
    def apsis_iter(self, interval: sgp4_predict.IntervalRange, *, step: typing.Optional[datetime.timedelta] = None) -> ApsisIter:
        r"""
        Iterate over apogee and perigee events within the interval.
        
        `interval` must expose `.start` and `.end` datetime properties.
        `step` is the fixed step used to scan for radial-velocity sign changes,
        defaulting to the library's own value.
        """
    def illumination_iter(self, interval: sgp4_predict.IntervalRange, *, step: typing.Optional[datetime.timedelta] = None, walk_step: typing.Optional[datetime.timedelta] = None, max_window_duration: typing.Optional[datetime.timedelta] = None) -> IlluminationIter:
        r"""
        Iterate over sunlit and eclipse windows within the interval.
        
        `interval` must expose `.start` and `.end` datetime properties.
        
        The keyword-only arguments tune the coarse scan; each defaults to the
        library's own value. `step` is the fixed step used to scan for
        shadow-boundary crossings and
        `walk_step` the one used to pin down a window's true start and end.
        An eclipse window longer than
        `max_window_duration` raises `RuntimeError`; sunlit windows are the gaps
        between eclipse windows and are never bounded by it.
        """
    def detect_transit(self, t: datetime.datetime, observer: GeodeticPoint, min_elevation_deg: builtins.float, *, walk_step: typing.Optional[datetime.timedelta] = None, max_transit_duration: typing.Optional[datetime.timedelta] = None) -> typing.Optional[Transit]:
        r"""
        Detect whether a transit is in progress at time `t`.
        
        Returns `None` if the satellite is below `min_elevation_deg` at `t`.
        Searches backward and forward to bracket AoS and LoS.
        
        Raises `RuntimeError` if the transit turns out to be longer than
        `max_transit_duration`, which defaults to one hour. See `transits_iter`;
        the other knobs there do not apply to this single-point detection.
        """
    def max_elevation(self, observer: GeodeticPoint, interval: sgp4_predict.IntervalRange, *, scan_step: typing.Optional[datetime.timedelta] = None) -> tuple[datetime.datetime, Observation]:
        r"""
        Find the peak elevation of the satellite over an observer within the interval.
        
        `interval` must expose `.start` and `.end` datetime properties.
        Returns `(datetime, Observation)` at the peak.
        Raises `RuntimeError` if no peak is found in the interval.
        
        `scan_step` is the fixed step used to scan for elevation-rate zero
        crossings, defaulting to the library's own value.
        """
    def illumination_state(self, t: datetime.datetime) -> IlluminationState:
        r"""
        Determine whether the satellite is sunlit or in eclipse at time `t`.
        """
    def tle_age_seconds(self, now: datetime.datetime) -> builtins.float:
        r"""
        Age of the TLE relative to `now` in seconds (positive = TLE is in the past).
        """

@typing.final
class Rectangle:
    r"""
    A latitude/longitude box, whose north and south edges follow their parallels
    exactly.
    
    The box runs **eastward** from the south-west corner, so a north-east corner at
    a smaller longitude wraps across the antimeridian. Corners may be `LatLon`
    objects, `GeodeticPoint` objects whose altitude is ignored, or
    `(latitude_deg, longitude_deg)` tuples.
    
    Raises `ValueError` if a latitude is outside [-90, 90], if a coordinate is `nan`
    or infinite, or if the box has no extent. Note that -180 and 180 are the same
    meridian, so use `latitude_band` for a box spanning every longitude.
    """
    @property
    def latitudes_deg(self) -> tuple[builtins.float, builtins.float]:
        r"""
        The southern and northern latitude bounds, in degrees.
        """
    @property
    def longitudes_deg(self) -> tuple[builtins.float, builtins.float]:
        r"""
        The western bound and the extent eastward from it, in degrees. The extent is
        360 for a box built by `latitude_band`.
        """
    def __new__(cls, south_west: sgp4_predict.LatLonLike, north_east: sgp4_predict.LatLonLike) -> Rectangle: ...
    @staticmethod
    def latitude_band(south_deg: builtins.float, north_deg: builtins.float) -> Rectangle:
        r"""
        A box spanning every longitude between two latitudes — a band, or a polar
        cap when one latitude is a pole.
        """
    def signed_angular_offset_deg(self, point: sgp4_predict.LatLonLike) -> builtins.float:
        r"""
        Signed angular offset of a point from the boundary, in degrees:
        positive inside, negative outside, zero on the boundary.
        """
    def max_angular_distance_deg(self, point: sgp4_predict.LatLonLike) -> builtins.float:
        r"""
        Angular distance from a point to the farthest point of the area, in
        degrees. This is what `coverage="full"` is measured against.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class Refinement:
    r"""
    Root-finder configuration used to refine detected event times.
    
    A bracketed hybrid solver: each iteration takes a Newton-Raphson step
    when a derivative is available and a secant/bisection step otherwise,
    converging once the crossing is pinned down to `time_tolerance` seconds.
    """
    @property
    def time_tolerance(self) -> builtins.float:
        r"""
        Convergence threshold on the crossing time, in seconds.
        """
    @time_tolerance.setter
    def time_tolerance(self, value: builtins.float) -> None: ...
    @property
    def max_iter(self) -> builtins.int:
        r"""
        Maximum number of solver iterations.
        """
    @max_iter.setter
    def max_iter(self, value: builtins.int) -> None: ...
    def __eq__(self, other: builtins.object, /) -> builtins.bool: ...
    def __new__(cls, *, time_tolerance: typing.Optional[builtins.float] = None, max_iter: typing.Optional[builtins.int] = None) -> Refinement:
        r"""
        Both arguments are keyword-only; either left unset keeps the library's
        default.
        """

@typing.final
class StateVectorEcef:
    r"""
    State vector in the Earth-Centred Earth-Fixed (ECEF) frame.
    Positions in metres, velocities in m/s.
    """
    @property
    def position(self) -> Vec3:
        r"""
        Position in the ECEF frame (metres).
        """
    @property
    def velocity(self) -> Vec3:
        r"""
        Velocity in the ECEF frame (m/s).
        """
    def __eq__(self, other: builtins.object, /) -> builtins.bool: ...
    def to_enu(self, observer: GeodeticPoint) -> StateVectorEnu:
        r"""
        Convert to the East-North-Up (ENU) frame relative to the given observer.
        """

@typing.final
class StateVectorEnu:
    r"""
    State vector in the East-North-Up (ENU) frame relative to a ground observer.
    Positions in metres, velocities in m/s.
    """
    @property
    def position(self) -> Vec3:
        r"""
        Position in the ENU frame (metres).
        """
    @property
    def velocity(self) -> Vec3:
        r"""
        Velocity in the ENU frame (m/s).
        """
    def __eq__(self, other: builtins.object, /) -> builtins.bool: ...
    def to_observation(self) -> Observation:
        r"""
        Convert to a ground observation (azimuth, elevation, range, range_rate).
        """

@typing.final
class StateVectorTeme:
    r"""
    State vector in the True Equator Mean Equinox (TEME) frame — the native SGP4 output frame.
    Positions in metres, velocities in m/s.
    """
    @property
    def position(self) -> Vec3:
        r"""
        Position in the TEME frame (metres).
        """
    @property
    def velocity(self) -> Vec3:
        r"""
        Velocity in the TEME frame (m/s).
        """
    def __eq__(self, other: builtins.object, /) -> builtins.bool: ...
    def to_ecef(self, t: datetime.datetime) -> StateVectorEcef:
        r"""
        Convert to the Earth-Centred Earth-Fixed (ECEF) frame at the given UTC time.
        """

@typing.final
class Tle:
    r"""
    A satellite TLE (Two-Line Element set) identified by a name and two TLE lines.
    """
    @property
    def satellite_name(self) -> builtins.str: ...
    @property
    def line_1(self) -> builtins.str: ...
    @property
    def line_2(self) -> builtins.str: ...
    def __eq__(self, other: builtins.object, /) -> builtins.bool: ...
    def __hash__(self) -> builtins.int: ...
    def __new__(cls, satellite_name: builtins.str, line_1: builtins.str, line_2: builtins.str) -> Tle: ...
    def to_elements(self) -> Elements:
        r"""
        Parse this TLE into orbital elements.
        
        Raises `ValueError` if the TLE is malformed.
        """

@typing.final
class Transit:
    r"""
    A satellite pass — the window during which the satellite is above the minimum elevation.
    """
    @property
    def start(self) -> datetime.datetime:
        r"""
        Acquisition of Signal: when the satellite rises above `min_elevation`.
        """
    @property
    def end(self) -> datetime.datetime:
        r"""
        Loss of Signal: when the satellite drops below `min_elevation`.
        """
    @property
    def duration(self) -> datetime.timedelta:
        r"""
        Length of the interval.
        """
    @property
    def mid_point(self) -> datetime.datetime:
        r"""
        The instant halfway between `start` and `end`.
        """
    @property
    def duration_seconds(self) -> builtins.float:
        r"""
        Duration of the transit in seconds.
        
        Deprecated: use `duration`, which is a `timedelta`.
        """
    def __eq__(self, other: builtins.object, /) -> builtins.bool: ...
    def __hash__(self) -> builtins.int: ...
    def intersection(self, other: sgp4_predict.IntervalRange) -> typing.Optional[Interval]:
        r"""
        The overlap with `other`, or None if the two do not overlap.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class TransitIter:
    r"""
    Lazy iterator yielding satellite passes visible to an observer.
    """
    def __iter__(self) -> TransitIter: ...
    def __next__(self) -> Transit: ...

@typing.final
class Vec3:
    r"""
    A 3-component vector (x, y, z).  Used for position (metres) and velocity (m/s).
    """
    @property
    def x(self) -> builtins.float: ...
    @property
    def y(self) -> builtins.float: ...
    @property
    def z(self) -> builtins.float: ...
    def __eq__(self, other: builtins.object, /) -> builtins.bool: ...
    def __new__(cls, x: builtins.float, y: builtins.float, z: builtins.float) -> Vec3: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class ApsisEvent(enum.Enum):
    r"""
    Whether an apsis event is apogee or perigee.
    """
    Apogee = ...
    r"""
    Point of greatest distance from Earth (maximum altitude).
    """
    Perigee = ...
    r"""
    Point of closest approach to Earth (minimum altitude).
    """

@typing.final
class Classification(enum.Enum):
    r"""
    Satellite classification type (CLASSIFICATION_TYPE field in OMM).
    """
    Unclassified = ...
    r"""
    Unclassified (U)
    """
    Classified = ...
    r"""
    Classified (C)
    """
    Secret = ...
    r"""
    Secret (S)
    """

@typing.final
class Coverage(enum.Enum):
    r"""
    Whether any part of an area, or all of it, must be within reach for a window
    to be open.
    """
    Any = ...
    r"""
    Any part of the area is within reach.
    """
    Full = ...
    r"""
    Every part of the area is within reach at once. Needs `max_off_nadir_deg`
    wider than the area — at the default of zero the reach is a single point,
    so no window opens. Not the same as "one image covers the area", which
    depends on the instantaneous field of view.
    """

@typing.final
class FillRule(enum.Enum):
    r"""
    How the interior of a self-intersecting `Polygon` is determined.
    """
    NonZero = ...
    r"""
    Inside wherever the winding number is non-zero. A ring that crosses itself stays filled.
    """
    EvenOdd = ...
    r"""
    Inside wherever the winding number is odd. A ring that doubles back leaves a hole.
    """

@typing.final
class IlluminationState(enum.Enum):
    r"""
    Whether the satellite is sunlit or in Earth's shadow.
    """
    Sunlit = ...
    r"""
    The satellite is illuminated by the Sun.
    """
    Eclipse = ...
    r"""
    The satellite is in Earth's shadow (cylindrical umbra model).
    """

